--Creating Database

USE Gradify_Database;
DROP TABLE ASSESSMENT;
DROP TABLE COURSE;
DROP TABLE SEMESTER;
DROP TABLE STUDENT;
CREATE TABLE Student (
	STUDENTID INT PRIMARY KEY IDENTITY(1,1), 
	STUDENT_NAME VARCHAR(200) NOT NULL,
	OriginalInputEmail VARCHAR(250) NOT NULL,
	EMAIL AS LOWER(OriginalInputEmail) PERSISTED UNIQUE,
	PASSWORD_HASH VARCHAR(250) NOT NULL,
	CREATED_AT DATETIME2 DEFAULT SYSDATETIME() NOT NULL,
	Verification_code INT NOT NULL,
	IsVerified BIT DEFAULT 0 NOT NULL,
	Verification_Code_Expire DATETIME2 NOT NULL,
	PublicId UNIQUEIDENTIFIER UNIQUE NOT NULL,
	RefreshToken varchar(100) Unique NOT NULL,
	RefreshToken_expire DATETIME2 NOT NULL,
	PASSWORD_TEMP_HASH VARCHAR(250),
	PASSWORD_TEMP_EXPIRE DATETIME2
	);

	
CREATE TABLE Semester(

	SEMESTERID INT PRIMARY KEY IDENTITY(1,1),
	STUDENTID INT FOREIGN KEY REFERENCES Student(STUDENTID) NOT NULL,
	SEMESTER_TERM VARCHAR(50) NOT NULL,
	SEMESTER_YEAR INT NOT NULL);


CREATE TABLE Course(

	COURSEID INT PRIMARY KEY IDENTITY(1,1),
	SEMESTERID INT FOREIGN KEY REFERENCES Semester(SEMESTERID),
	COURSE_CODE VARCHAR(10) NOT NULL,
	COURSE_NAME VARCHAR(350) NOT NULL,
	COURSE_WEIGHT DECIMAL(5,2) NOT NULL);


CREATE TABLE Assessment(
	ASSESSMENTID INT PRIMARY KEY IDENTITY(1,1),
	ASSESSMENTGROUPID INT NOT NULL,
	COURSEID INT FOREIGN KEY REFERENCES Course(COURSEID),
	ASSESSMENT_NAME VARCHAR(300) NOT NULL,
	ASSESSMENT_WEIGHT DECIMAL(5,2) NOT NULL,
	ASSESSMENT_GRADE DECIMAL(5,2) CHECK (ASSESSMENT_GRADE >=0 AND ASSESSMENT_GRADE <=100));

DELETE FROM STUDENT;
DELETE FROM SEMESTER;
DELETE FROM COURSE;
DELETE FROM ASSESSMENT;

--ADDING DUMMY INFO
INSERT INTO Student (STUDENT_NAME, EMAIL, PASSWORD_HASH)
VALUES 
('Cheran Balakrishnan', 'cheran@example.com', 'hashed_password_123');

INSERT INTO Semester (STUDENTID, SEMESTER_TERM, SEMESTER_YEAR)
VALUES
(1, 'Fall', 2024),
(1, 'Winter', 2025);

INSERT INTO Course (SEMESTERID, COURSE_CODE, COURSE_NAME, COURSE_WEIGHT)
VALUES
(1, 'CPS109', 'Computer Science I', 1),
(1, 'MTH140', 'Calculus I', 1),
(1, 'CPS209', 'Computer Science II', 1);

INSERT INTO Assessment (COURSEID, ASSESSMENT_NAME, ASSESSMENT_WEIGHT, ASSESSMENT_GRADE)
VALUES
(1, 'Midterm Exam', 5, 78),
(1, 'Labs', 5, 90),
(1, 'Final Exam', 5, NULL);


--VIEWING TABLE --

SELECT * FROM Student;
SELECT * from Semester;
SELECT * FROM Course;
SELECT * FROM Assessment;
--  Query 1 : Login Query -- 

SELECT STUDENTID, STUDENT_NAME 

FROM STUDENT 

WHERE EMAIL = 'cheran@example.com' and PASSWORD_HASH = 'hashed_password_123';


-- Query 2 : get student semester data --

SELECT SEMESTERID,SEMESTER_TERM, SEMESTER_YEAR

FROM SEMESTER 

WHERE STUDENTID = 1;

-- Query 3 : get course data --

SELECT COURSEID, COURSE_CODE, COURSE_NAME, COURSE_WEIGHT

FROM COURSE

WHERE SEMESTERID = 1

-- Query 4 : get assessment data --

SELECT ASSESSMENTID, ASSESSMENT_NAME, ASSESSMENT_WEIGHT,ASSESSMENT_GRADE

FROM ASSESSMENT

WHERE COURSEID = 1;


-- System triggers --

--Trigger 1: Do not allow assessment total weight to exceed 100%

CREATE TRIGGER Update_assessment
ON Assessment 
AFTER INSERT
AS
BEGIN
	DECLARE @total_weight DECIMAL;
	SELECT @total_weight = sum(ASSESSMENT_WEIGHT) from ASSESSMENT;
	
	IF @total_weight >= 100

	BEGIN
		ROLLBACK TRANSACTION;
		RAISERROR('Inserted assessments weight exceeds the entire course weighting to over 100.', 16 ,1);
	END

END;

--Trigger 2: Course limit per semester

CREATE TRIGGER COURSE_LIMIT
ON COURSE
AFTER INSERT 
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM COURSE
		WHERE SEMESTERID IN (SELECT SEMESTERID FROM INSERTED)
		GROUP BY SEMESTERID
		HAVING COUNT(*) > 10
		)
	BEGIN
		ROLLBACK TRANSACTION;
		RAISERROR('Inserted course exceeds course limit per semester', 16 ,1);
	END

END;

--Trigger 3: ASSESSMENT limit per COURSE 
CREATE TRIGGER ASSESSMENT_LIMIT
ON ASSESSMENT
AFTER INSERT 
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM ASSESSMENT
		WHERE COURSEID IN (SELECT COURSEID FROM INSERTED)
		GROUP BY COURSEID
		HAVING COUNT(*) > 25
		)
	BEGIN
		ROLLBACK TRANSACTION;
		RAISERROR('Inserted assessment exceeds assessment limit per course', 16 ,1);
	END

END;



--Trigger 4: SEMESTER limit per STUDENT

CREATE TRIGGER SEMESTER_LIMIT
ON SEMESTER
AFTER INSERT 
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM SEMESTER
		WHERE STUDENTID IN (SELECT STUDENTID FROM INSERTED)
		GROUP BY STUDENTID
		HAVING COUNT(*) > 5
		)
	BEGIN
		ROLLBACK TRANSACTION;
		RAISERROR('Inserted semester exceeds semester limit per student', 16 ,1);
	END

END;
